import { Industry, Position } from "../../api/companies";
import { Programme } from "../../api/students";

export const POSITIONS = [
  { label: "Thesis", value: Position.Thesis },
  { label: "Trainee Employment", value: Position.TraineeEmployment },
  { label: "Internship", value: Position.Internship },
  { label: "Summer job", value: Position.SummerJob },
  { label: "Foreign opportunity", value: Position.ForeignOppurtunity },
  { label: "Part time", value: Position.PartTime },
]

export const INDUSTRIES = [
  { label: "Electricity/energy/power"   , value: Industry.ElectricityEnergyPower },
  { label: "Environment"              , value: Industry.Environment },
  { label: "Banking/finance"           , value: Industry.BankingFinance },
  { label: "Union"                    , value: Industry.Union },
  { label: "Investment"               , value: Industry.Investment},
  { label: "Insurance"                , value: Industry.Insurance },
  { label: "Recruitment"              , value: Industry.Recruitment },
  { label: "Construction"             , value: Industry.Construction },
  { label: "Architecture"             , value: Industry.Architecture },
  { label: "Graphic design"            , value: Industry.GraphicDesign },
  { label: "Data/IT"                   , value: Industry.DataIT },
  { label: "Finance consultancy"       , value: Industry.FinanceConsultancy },
  { label: "Telecommunication"        , value: Industry.Telecommunication },
  { label: "Consulting"               , value: Industry.Consulting },
  { label: "Management"               , value: Industry.Management },
  { label: "Media"                    , value: Industry.Media },
  { label: "Industry"                 , value: Industry.Industry },
  { label: "Nuclear power"             , value: Industry.NuclearPower },
  { label: "Life science"              , value: Industry.LifeScience },
  { label: "Medical techniques"        , value: Industry.MedicalTechniques },
  { label: "Property infrastructure"   , value: Industry.PropertyInfrastructure },
  { label: "Research"                 , value: Industry.Research },
  { label: "Coaching"                 , value: Industry.Coaching },
]

export const PROGRAMS = [
  { label: "Architecture"   , value: Programme.Arkitekt },
  { label: "Industrial design"   , value: Programme.Industridesign },
  { label: "Construction and Railway construction"   , value: Programme.Byggteknik_med_Järnvägsteknik },
  { label: "Construction and architecture"   , value: Programme.Byggteknik_med_arkitektur },
  { label: "Construction and road"   , value: Programme.Byggteknik_med_väg_och_trafikteknik },
  { label: "Computer/Software engineering"   , value: Programme.Datateknik},
  { label: "Engineering Information and comunication"   , value: Programme.Informations_och_Kommunikationsteknik },
  { label: "Electrical engineering"   , value: Programme.Elektroteknik },
  { label: "Medical engineering"   , value: Programme.Medicinteknik },
  { label: "Industrial economics"   , value: Programme.Industriell_ekonomi },
  { label: "Ecological engineering"   , value: Programme.Ekosystemteknik },
  { label: "Chemical engineering"   , value: Programme.Kemiteknik },
  { label: "Engineering Biotechnology"   , value: Programme.Bioteknik },
  { label: "Land surveying"   , value: Programme.Lantmäteri },
  { label: "Fire engineer"   , value: Programme.Brandingenjör}, 
  { label: "Civil engineering"   , value: Programme.Väg_och_vatttenbyggnad },
  { label: "Mechanical engineering"   , value: Programme.Maskinteknik },
  { label: "Mechanical engineering with technical design"   , value: Programme.Maskinteknik_Teknisk_Design },
  { label: "Engineering Nanoscience"   , value: Programme.Nanoveteknik },
  { label: "Engineering Physcics"   , value: Programme.Teknisk_Fysik },
  { label: "Engineering Mathematics"   , value: Programme.Teknisk_Matematik },
]