import { Industry, Position } from "@/api/companies";
import { Programme } from "@/api/students";

export const POSITIONS = [
  { label: "Thesis", value: Position.Thesis },
  { label: "Trainee Employment", value: Position.TraineeEmployment },
  { label: "Internship", value: Position.Internship },
  { label: "Summer job", value: Position.SummerJob },
  { label: "Foreign opportunity", value: Position.ForeignOppurtunity },
  { label: "Part time", value: Position.PartTime },
]

export const INDUSTRIES = [
  { label: "Electricity/energy/power"   , value: Industry.ElectricityEnergyPower },
  { label: "Environment"              , value: Industry.Environment },
  { label: "Banking/finance"           , value: Industry.BankingFinance },
  { label: "Union"                    , value: Industry.Union },
  { label: "Investment"               , value: Industry.Investment},
  { label: "Insurance"                , value: Industry.Insurance },
  { label: "Recruitment"              , value: Industry.Recruitment },
  { label: "Construction"             , value: Industry.Construction },
  { label: "Architecture"             , value: Industry.Architecture },
  { label: "Graphic design"            , value: Industry.GraphicDesign },
  { label: "Data/IT"                   , value: Industry.DataIT },
  { label: "Finance consultancy"       , value: Industry.FinanceConsultancy },
  { label: "Telecommunication"        , value: Industry.Telecommunication },
  { label: "Consulting"               , value: Industry.Consulting },
  { label: "Management"               , value: Industry.Management },
  { label: "Media"                    , value: Industry.Media },
  { label: "Industry"                 , value: Industry.Industry },
  { label: "Nuclear power"             , value: Industry.NuclearPower },
  { label: "Life science"              , value: Industry.LifeScience },
  { label: "Medical techniques"        , value: Industry.MedicalTechniques },
  { label: "Property infrastructure"   , value: Industry.PropertyInfrastructure },
  { label: "Research"                 , value: Industry.Research },
  { label: "Coaching"                 , value: Industry.Coaching },
]

export const PROGRAMS = [
  { label: "A"   , value: 100}, 
  { label: "D"   , value: 101 },
  { label: "E"   , value: 102 },
  { label: "F"   , value: 103 },
  { label: "I"   , value: 104 },
  { label: "ING"   , value: 105 },
  { label: "K"   , value: 106 },
  { label: "M"   , value: 107 },
  { label: "V"   , value: 108 },
  { label: "W"   , value: 109 },
  { label: "Fire engineer"   , value: Programme.Fire_engineer },
  { label: "Mechanical engineering with technical design"   , value: Programme.Mechanical_engineering_with_technical_design },
  { label: "Electrical engineering"   , value: Programme.Electrical_engineering },
  { label: "Ecological engineering"   , value: Programme.Ecological_engineering },
  { label: "Mechanical engineering"   , value: Programme.Mechanical_engineering },
  { label: "Engineering Nanoscience"   , value: Programme.Engineering_Nanoscience },
  { label: "Engineering Biotechnology"   , value: Programme.Engineering_Biotechnology },
  { label: "Industrial design"   , value: Programme.Industrial_design },
  { label: "Architecture"   , value: Programme.Architecture },
  { label: "Engineering Information and comunication"   , value: Programme.Engineering_Information_and_comunication },
  { label: "Chemical engineering"   , value: Programme.Chemical_engineering },
  { label: "Construction and Railway construction"   , value: Programme.Construction_and_Railway_construction },
  { label: "Road and Water construction"   , value: Programme.Road_and_Water_construction },
  { label: "Construction and architecture"   , value: Programme.Construction_and_architecture },
  { label: "Industrial economics"   , value: Programme.Industrial_economics },
  { label: "Engineering Mathematics"   , value: Programme.Engineering_Mathematics },
  { label: "Medical engineering"   , value: Programme.Medical_engineering },
  { label: "Land surveying"   , value: Programme.Land_surveying },
  { label: "Computer Software engineering"   , value: Programme.Computer_Software_engineering },
  { label: "Engineering Physics"   , value: Programme.Engineering_Physics },
  { label: "Construction and road"   , value: Programme.Construction_and_road },
]